/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import LOGIC.Employee;
import javax.swing.JOptionPane;

/**
 *
 * @author danalajmi
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFeildFName = new javax.swing.JTextField();
        FNameLbl = new javax.swing.JLabel();
        FNameLbl1 = new javax.swing.JLabel();
        txtFeildLName = new javax.swing.JTextField();
        FNameLbl2 = new javax.swing.JLabel();
        txtFeildAddress = new javax.swing.JTextField();
        FNameLbl3 = new javax.swing.JLabel();
        txtFeildPhone = new javax.swing.JTextField();
        FNameLbl4 = new javax.swing.JLabel();
        txtFeildSalary = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Kefa III", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Employee");

        txtFeildFName.setColumns(10);
        txtFeildFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeildFNameActionPerformed(evt);
            }
        });

        FNameLbl.setText("Enter First name");

        FNameLbl1.setText("Enter last name");

        txtFeildLName.setColumns(10);
        txtFeildLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeildLNameActionPerformed(evt);
            }
        });

        FNameLbl2.setText("Enter address");

        txtFeildAddress.setColumns(10);
        txtFeildAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeildAddressActionPerformed(evt);
            }
        });

        FNameLbl3.setText("Enter phone number");

        txtFeildPhone.setColumns(10);
        txtFeildPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeildPhoneActionPerformed(evt);
            }
        });

        FNameLbl4.setText("Enter employee salary");

        txtFeildSalary.setColumns(10);
        txtFeildSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeildSalaryActionPerformed(evt);
            }
        });

        jButton1.setText("Save Employee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(FNameLbl4)
                                    .addGap(47, 47, 47)
                                    .addComponent(txtFeildSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(FNameLbl1)
                                .addComponent(FNameLbl)
                                .addComponent(FNameLbl2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FNameLbl3)
                                .addGap(59, 59, 59)
                                .addComponent(txtFeildPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jButton1)))
                .addContainerGap(263, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFeildFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtFeildLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFeildAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(264, 264, 264))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFeildFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNameLbl))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFeildLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNameLbl1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFeildAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNameLbl2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFeildPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNameLbl3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFeildSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNameLbl4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFeildFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeildFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeildFNameActionPerformed

    private void txtFeildLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeildLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeildLNameActionPerformed

    private void txtFeildAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeildAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeildAddressActionPerformed

    private void txtFeildPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeildPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeildPhoneActionPerformed

    private void txtFeildSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeildSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeildSalaryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        String fname = txtFeildFName.getText();
        String lname = txtFeildLName.getText();
        String address = txtFeildAddress.getText();
        int phone = Integer.parseInt(txtFeildPhone.getText());
        double salary = Double.parseDouble(txtFeildSalary.getText());
        Employee newEmployee = new Employee(salary, fname, lname, address, phone);
        // this only runs if the employee was successfully created and no exception occured
         JOptionPane.showMessageDialog(rootPane, newEmployee.getStaffID() +" Created successfully", "Successful", 1);
         // reset all fields 
        txtFeildFName.setText(null);
        txtFeildLName.setText(null);
        txtFeildAddress.setText(null);
        txtFeildPhone.setText(null);
        txtFeildSalary.setText(null);
          
            
        }catch (NumberFormatException ex){
        JOptionPane.showMessageDialog(rootPane, ex, "Error", 0);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FNameLbl;
    private javax.swing.JLabel FNameLbl1;
    private javax.swing.JLabel FNameLbl2;
    private javax.swing.JLabel FNameLbl3;
    private javax.swing.JLabel FNameLbl4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtFeildAddress;
    private javax.swing.JTextField txtFeildFName;
    private javax.swing.JTextField txtFeildLName;
    private javax.swing.JTextField txtFeildPhone;
    private javax.swing.JTextField txtFeildSalary;
    // End of variables declaration//GEN-END:variables
}
