/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import LOGIC.Employee;
import LOGIC.Gym;
import LOGIC.Member;
import LOGIC.Staff;
import LOGIC.Student;
import LOGIC.Trainer;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author danalajmi
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     *
     * @throws java.io.IOException
     */
    public MainWindow() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
        loadDATFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnEmployee = new javax.swing.JButton();
        btnMember = new javax.swing.JButton();
        btnCleanStart = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Publico Text", 1, 24)); // NOI18N
        jLabel2.setText("Bahrain Polytechnic Gym");

        btnEmployee.setText("Employee Management");
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });

        btnMember.setText("Member Management");
        btnMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberActionPerformed(evt);
            }
        });

        btnCleanStart.setText("Clean start");
        btnCleanStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanStartActionPerformed(evt);
            }
        });

        btnReport.setText("Generate report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEmployee)
                            .addComponent(jLabel2))
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMember)
                        .addGap(53, 53, 53))))
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReport)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCleanStart)
                        .addGap(18, 18, 18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmployee)
                    .addComponent(btnMember))
                .addGap(18, 18, 18)
                .addComponent(btnReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnCleanStart)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        String title = "Bahrain Polytechnic GYM report \n";
        try {
            FileWriter reportFile = new FileWriter("report.txt");
            reportFile.write(title);
            reportFile.write("Polytechnic staff \n");

            int staffCount = 0;
            for (Member member : Gym.getMembersList()) {
                if (member instanceof Staff) {
                    staffCount++;
                    String staffInfo = staffCount + ".Name: " + member.getfName() + " " + member.getlName()
                            + "\n \t address: " + member.getAddress() + "\n \t Phone Number: " + member.getPhone() 
                            + "\n \t Department: " + ((Staff) member).getDepartment() + "\n \t Position: " + ((Staff) member).getPosition() + "\n";
                    reportFile.write(staffInfo);
                }
            }
                reportFile.write("\nTotal staff members: " + staffCount);
                
                reportFile.write("\n \nPolytechnic students \n");

            int studentCount = 0;
            for (Member member : Gym.getMembersList()) {
                if (member instanceof Student) {
                    studentCount++;
                    String studentInfo = studentCount + ".Name: " + member.getfName() + " " + member.getlName()
                            + "\n \t address: " + member.getAddress() + "\n \t Phone Number: " + member.getPhone() 
                            + "\n \t Enrolled course: " + ((Student) member).getCourse() + "\n \t Team: " + ((Student) member).getTeam() + "\n";
                    reportFile.write(studentInfo);
                }
                
            }
            reportFile.write("\nTotal student members: " + studentCount);
            reportFile.close();
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnReportActionPerformed

    private void loadDATFile() throws FileNotFoundException, IOException, ClassNotFoundException {
        Path pathEmp = Paths.get("employees.dat");
        Path pathMember = Paths.get("members.dat");
        if (Files.exists(pathEmp) || Files.exists(pathMember)) {

            FileInputStream fileInEmp;
            try {
                fileInEmp = new FileInputStream("employees.dat");
                ObjectInputStream inEmp = new ObjectInputStream(fileInEmp);
                Gym.setEmployeesList((ArrayList<Employee>) inEmp.readObject());
            } catch (FileNotFoundException e) {
                fileInEmp = null;
            }
            FileInputStream fileInMember;
            try {
                fileInMember = new FileInputStream("members.dat");
                ObjectInputStream inMember = new ObjectInputStream(fileInMember);
                Gym.setMembersList((ArrayList<Member>) inMember.readObject());

            } catch (FileNotFoundException e) {
                fileInMember = null;
            } catch (ClassNotFoundException ex) {
                System.out.println("class not found");
            }

        } else {
            try {
                loadStartUpFile();
            } catch (IOException ex) {
                Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    private void loadStartUpFile() throws FileNotFoundException, IOException, ClassNotFoundException {
        Path pathEmp = Paths.get("employees.dat");
        Path pathMember = Paths.get("members.dat");
        if (Files.exists(pathEmp) || Files.exists(pathMember)) {
            File empFile = new File("employees.dat");
            File memberFile = new File("members.dat");
            empFile.delete();
            memberFile.delete();
        }

        try {
            File startUpFile = new File("startup.txt");
            ArrayList<Employee> gymemployees = new ArrayList<>();
            Scanner scan = new Scanner(startUpFile);
            int employeeCount = Integer.parseInt(scan.nextLine());
            for (int i = 0; i < employeeCount; i++) {
                Employee newEmp = null;
                String empType = scan.nextLine();
                String fname = scan.nextLine();
                String lname = scan.nextLine();
                String address = scan.nextLine();
                int phone = Integer.parseInt(scan.nextLine());
                double salary = Double.parseDouble(scan.nextLine());
                if (empType.equals("PT")) {
                    newEmp = new Trainer(salary, fname, lname, address, phone, empType);
                    int membersCount = Integer.parseInt(scan.nextLine());
                    for (int j = 0; j < membersCount; j++) {
                        Member newMember = null;
                        String memType = scan.nextLine();
                        String memFName = scan.nextLine();
                        String memLName = scan.nextLine();
                        String memaddress = scan.nextLine();
                        String memdob = scan.nextLine();
                        int memphone = Integer.parseInt(scan.nextLine());
                        String gender = scan.nextLine();
                        if (memType.equals("staff")) {
                            String position = scan.nextLine();
                            String department = scan.nextLine();
                            newMember = new Staff(position, department, memdob, gender, memType, memFName, memLName,
                                    memaddress, memphone);
                        } else if (memType.equals("student")) {
                            String degree = scan.nextLine();
                            String team = scan.nextLine();
                            newMember = new Student(degree, team, degree, gender, team, memFName, memLName, memaddress,
                                    memphone);
                        }
                        Trainer trainer = (Trainer) newEmp;
                        trainer.addMember(newMember);
                        Gym.addMember(newMember);
                    }
                } else {
                    newEmp = new Employee(salary, fname, lname, address, phone, empType);
                }
                gymemployees.add(newEmp);
                Gym.setEmployeesList(gymemployees);

            }
            try {
                FileOutputStream fileOut = new FileOutputStream("employees.dat");
                ObjectOutputStream out = new ObjectOutputStream(fileOut);
                out.writeObject(Gym.getEmployeesList());

            } catch (FileNotFoundException ex) {
                Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                FileOutputStream memFileOut = new FileOutputStream("members.dat");
                ObjectOutputStream memOut = new ObjectOutputStream(memFileOut);
                memOut.writeObject(Gym.getMembersList());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }
            loadDATFile();
        } catch (IOException ex) {
            Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEmployeeActionPerformed
        // TODO add your handling code here:
        EmployeeDisplay empDis = new EmployeeDisplay();
        empDis.setVisible(true);
        this.setVisible(false);
    }// GEN-LAST:event_btnEmployeeActionPerformed

    private void btnMemberActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMemberActionPerformed
        // TODO add your handling code here:
        MemberDisplay memberDisplay = new MemberDisplay();
        memberDisplay.setVisible(true);
        this.setVisible(false);
    }// GEN-LAST:event_btnMemberActionPerformed

    /**
     *
     * @param evt
     */
    private void btnCleanStartActionPerformed(java.awt.event.ActionEvent evt) throws IOException, ClassNotFoundException {// GEN-FIRST:event_btnCleanStartActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to initialise a fresh start");
        try {
            Gym.getMembersList().clear();
            Gym.getEmployeesList().clear();
            loadStartUpFile();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_btnCleanStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainWindow().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCleanStart;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnMember;
    private javax.swing.JButton btnReport;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
