package GUI;

/**
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt
 * to change this license Click
 * nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this
 * template
 */
import GUI.MainWindow;
import LOGIC.Gym;
import LOGIC.Staff;
import LOGIC.Student;
import LOGIC.Employee;
import LOGIC.Member;
import LOGIC.Trainer;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.RootPaneUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danalajmi
 */
public class MemberDisplay extends javax.swing.JFrame {

    /**
     * Creates new form MemberDisplay
     */
    public MemberDisplay() {
        initComponents();
        AddTrainers();
        loadTrainerMembers();
        loadUnassignedMembers();
        initialiseCombo();

    }

    /**
     * Name: AddTrainers
     *
     * @author Fatima Alrafaei Purpose/description: gets the list of trainers
     * and loads them in the appropriate comboboxes
     */
    public void AddTrainers() {
        int i = 0;
        do {
            Employee employee = Gym.getEmployeesList().get(i);
            if (employee instanceof Trainer) {
                Trainer trainer = (Trainer) employee;
                String fullName = trainer.getfName() + " " + trainer.getlName();
                TrainerComboBox.addItem(fullName);
                TrainerComboBox2.addItem(fullName);

            }
            i++;
        } while (i < Gym.getEmployeesList().size());
    }

    /**
     * Name: loadTrianerMembers
     *
     *
     * @author Fatima Alrefaei Purpose/description: gets the list of members
     * assigned to the selected trainer
     */
    public void loadTrainerMembers() {
        if (TrainerComboBox.getSelectedItem() != null) {
            TrainerMemberComboBox.removeAllItems();
            String selectedTrainer = TrainerComboBox.getSelectedItem().toString();
            for (Employee employee : Gym.getEmployeesList()) {
                if (employee instanceof Trainer) {
                    Trainer trainer = (Trainer) employee;
                    String trainerName = trainer.getfName() + " " + trainer.getlName();
                    if (trainerName.equals(selectedTrainer)) {
                        if (trainer.getAssignedMembers() != null) {
                            for (Member member : trainer.getAssignedMembers()) {
                                String memberName = member.getfName() + " " + member.getlName();
                                TrainerMemberComboBox.addItem(memberName);
                            }
                        }

                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        TrainerComboBox = new javax.swing.JComboBox<>();
        AssignTrainerButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MemberComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        TrainerComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TrainerMemberComboBox = new javax.swing.JComboBox<>();
        RemoveMemberButton1 = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblAlterMemberTitle = new javax.swing.JLabel();
        lblFnameM_E = new javax.swing.JLabel();
        txtGenderM_E = new javax.swing.JTextField();
        lblLNameM_E = new javax.swing.JLabel();
        txtLNameM_E = new javax.swing.JTextField();
        lbladdressM_E = new javax.swing.JLabel();
        txtaddressM_E = new javax.swing.JTextField();
        lblPhoneM_E = new javax.swing.JLabel();
        txtPhoneM_E = new javax.swing.JTextField();
        lblDOBM_E = new javax.swing.JLabel();
        txtDOBM_E = new javax.swing.JTextField();
        lblGenderM_E = new javax.swing.JLabel();
        jRadioButtonWM_E = new javax.swing.JRadioButton();
        jRadioButtonMM_E = new javax.swing.JRadioButton();
        btnAlterMemeberSave = new javax.swing.JButton();
        jComboBoxMembersID = new javax.swing.JComboBox<>();
        txtfNameM_E = new javax.swing.JTextField();
        pnlJoin = new javax.swing.JPanel();
        pnlStaff1 = new javax.swing.JPanel();
        lblPosition1 = new javax.swing.JLabel();
        txtPosition1 = new javax.swing.JTextField();
        lblDepartment1 = new javax.swing.JLabel();
        jComboBoxDep1 = new javax.swing.JComboBox<>();
        txtDisplayDepartment = new javax.swing.JTextField();
        pnlStudent1 = new javax.swing.JPanel();
        lblStuduyCourseM_E = new javax.swing.JLabel();
        ComboBoxCourseM_E = new javax.swing.JComboBox<>();
        lblSportTeamM_E = new javax.swing.JLabel();
        ComboBoxTeamM_E = new javax.swing.JComboBox<>();
        txtTeamDisplyM_E = new javax.swing.JTextField();
        txtCourseDisplyM_E = new javax.swing.JTextField();
        lblFnameM_E1 = new javax.swing.JLabel();
        txtMemberTypeM_E = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMembers = new javax.swing.JTable();
        jButtonDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFname1 = new javax.swing.JLabel();
        txtfName1 = new javax.swing.JTextField();
        lblLName1 = new javax.swing.JLabel();
        txtLName1 = new javax.swing.JTextField();
        lbladdress1 = new javax.swing.JLabel();
        txtaddress1 = new javax.swing.JTextField();
        lblPhone1 = new javax.swing.JLabel();
        txtPhone1 = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonW = new javax.swing.JRadioButton();
        jRadioButtonM = new javax.swing.JRadioButton();
        btnAddMemeber = new javax.swing.JButton();
        jRadioButtonStaff = new javax.swing.JRadioButton();
        jRadioButtonStudent = new javax.swing.JRadioButton();
        pnlMemberType = new javax.swing.JPanel();
        pnlStudent = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxCourse = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonTeamY = new javax.swing.JRadioButton();
        jRadioButtonTeamN = new javax.swing.JRadioButton();
        pnlTeam = new javax.swing.JPanel();
        jComboBoxTeam = new javax.swing.JComboBox<>();
        pnlStaff = new javax.swing.JPanel();
        lblPosition = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();
        jComboBoxDep = new javax.swing.JComboBox<>();
        btnHome = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        TrainerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainerComboBoxActionPerformed(evt);
            }
        });

        AssignTrainerButton.setText("Assign");
        AssignTrainerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignTrainerButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Select a member");

        jLabel6.setText("Select a Trainer");

        MemberComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberComboBoxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel9.setText("Assign a Trainer to a Member ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MemberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TrainerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssignTrainerButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel9)))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel9)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MemberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TrainerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(AssignTrainerButton)
                .addContainerGap(886, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Assign Trainer ", jPanel1);

        TrainerComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainerComboBox2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Select Trainer ");

        jLabel8.setText("Select the member you want to remove");

        TrainerMemberComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainerMemberComboBoxActionPerformed(evt);
            }
        });

        RemoveMemberButton1.setText("Remove");
        RemoveMemberButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveMemberButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel10.setText("Remove a Member fram a Trainer List");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(19, 19, 19)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TrainerMemberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TrainerComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RemoveMemberButton1)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel10)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel10)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TrainerComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TrainerMemberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(RemoveMemberButton1)
                .addContainerGap(877, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Remove Member ", jPanel3);

        lblAlterMemberTitle.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblAlterMemberTitle.setText("Alter Member's Information");

        lblFnameM_E.setText("First name: ");

        txtGenderM_E.setColumns(10);

        lblLNameM_E.setText("Last name: ");

        txtLNameM_E.setColumns(10);

        lbladdressM_E.setText("address");

        txtaddressM_E.setColumns(10);

        lblPhoneM_E.setText("phone Number");

        txtPhoneM_E.setColumns(10);

        lblDOBM_E.setText("Date of birth");

        txtDOBM_E.setColumns(10);
        txtDOBM_E.setText("DD/MM/YYYY");

        lblGenderM_E.setText("Gender: ");

        buttonGroup3.add(jRadioButtonWM_E);
        jRadioButtonWM_E.setText("Female");

        buttonGroup3.add(jRadioButtonMM_E);
        jRadioButtonMM_E.setText("Male");

        btnAlterMemeberSave.setText("Save");
        btnAlterMemeberSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterMemeberSaveActionPerformed(evt);
            }
        });

        jComboBoxMembersID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMembersIDActionPerformed(evt);
            }
        });

        txtfNameM_E.setColumns(10);

        lblPosition1.setText("Department");

        txtPosition1.setColumns(10);

        lblDepartment1.setText("Position");

        jComboBoxDep1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT", "Creative Media", "Engineering", "Business", "Adminstration", "Health & sanitary", "Services" }));
        jComboBoxDep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDep1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStaff1Layout = new javax.swing.GroupLayout(pnlStaff1);
        pnlStaff1.setLayout(pnlStaff1Layout);
        pnlStaff1Layout.setHorizontalGroup(
            pnlStaff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaff1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStaff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPosition1)
                    .addComponent(lblDepartment1))
                .addGap(18, 18, 18)
                .addGroup(pnlStaff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStaff1Layout.createSequentialGroup()
                        .addComponent(txtDisplayDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxDep1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlStaff1Layout.createSequentialGroup()
                        .addComponent(txtPosition1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlStaff1Layout.setVerticalGroup(
            pnlStaff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaff1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlStaff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPosition1)
                    .addComponent(jComboBoxDep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDisplayDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStaff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment1)
                    .addComponent(txtPosition1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlStudent1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStuduyCourseM_E.setText("Study Course");
        pnlStudent1.add(lblStuduyCourseM_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        ComboBoxCourseM_E.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT. Programming", "ICT. Cyber Security", "ICT. Network", "ICT. DataBase" }));
        ComboBoxCourseM_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCourseM_EActionPerformed(evt);
            }
        });
        pnlStudent1.add(ComboBoxCourseM_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 130, -1));

        lblSportTeamM_E.setText("Your Sport Team");
        pnlStudent1.add(lblSportTeamM_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        ComboBoxTeamM_E.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vollyball", "basketball", "football", "running", "tennis" }));
        ComboBoxTeamM_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTeamM_EActionPerformed(evt);
            }
        });
        pnlStudent1.add(ComboBoxTeamM_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        txtTeamDisplyM_E.setColumns(10);
        txtTeamDisplyM_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeamDisplyM_EActionPerformed(evt);
            }
        });
        pnlStudent1.add(txtTeamDisplyM_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 110, -1));
        pnlStudent1.add(txtCourseDisplyM_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 120, -1));

        javax.swing.GroupLayout pnlJoinLayout = new javax.swing.GroupLayout(pnlJoin);
        pnlJoin.setLayout(pnlJoinLayout);
        pnlJoinLayout.setHorizontalGroup(
            pnlJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJoinLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pnlStudent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlJoinLayout.createSequentialGroup()
                .addComponent(pnlStaff1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        pnlJoinLayout.setVerticalGroup(
            pnlJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJoinLayout.createSequentialGroup()
                .addComponent(pnlStaff1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlStudent1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblFnameM_E1.setText("Please Choose The ID Of The Member You Wish To change Threir Information :");

        txtMemberTypeM_E.setColumns(10);

        jLabel11.setText("Member Type :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(lblAlterMemberTitle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAlterMemeberSave, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblGenderM_E)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGap(122, 122, 122)
                                            .addComponent(txtGenderM_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioButtonMM_E)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButtonWM_E))
                                .addComponent(lblDOBM_E)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFnameM_E)
                                            .addComponent(lblLNameM_E))
                                        .addGap(62, 62, 62)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtLNameM_E)
                                            .addComponent(txtfNameM_E)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(lbladdressM_E)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtaddressM_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(lblPhoneM_E)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPhoneM_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDOBM_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMemberTypeM_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlJoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(168, 168, 168))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(lblFnameM_E1)
                .addGap(29, 29, 29)
                .addComponent(jComboBoxMembersID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAlterMemberTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMembersID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFnameM_E1))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFnameM_E)
                            .addComponent(txtfNameM_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLNameM_E)
                            .addComponent(txtLNameM_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbladdressM_E)
                            .addComponent(txtaddressM_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhoneM_E)
                            .addComponent(txtPhoneM_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDOBM_E)
                            .addComponent(txtDOBM_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMemberTypeM_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addComponent(pnlJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenderM_E)
                    .addComponent(jRadioButtonWM_E)
                    .addComponent(jRadioButtonMM_E)
                    .addComponent(txtGenderM_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnAlterMemeberSave)
                .addGap(894, 894, 894))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alter Member's Information", jPanel4);

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel13.setText("Delete Members");

        jLabel12.setText("This feature will delete membership of members from the gym");

        jTableMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Membership ID", "First Name", "Last Name", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMembers);

        jButtonDelete.setText("Delete Membership");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(307, 307, 307))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jButtonDelete)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonDelete)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Delete Members", jPanel6);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Add member");

        lblFname1.setText("First name: ");

        txtfName1.setColumns(10);

        lblLName1.setText("Last name: ");

        txtLName1.setColumns(10);

        lbladdress1.setText("address");

        txtaddress1.setColumns(10);

        lblPhone1.setText("phone Number");

        txtPhone1.setColumns(10);

        lblDOB.setText("Date of birth");

        txtDOB.setColumns(10);
        txtDOB.setText("DD/MM/YYYY");
        txtDOB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDOBMouseClicked(evt);
            }
        });

        jLabel3.setText("Gender: ");

        buttonGroup2.add(jRadioButtonW);
        jRadioButtonW.setText("Woman");
        jRadioButtonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonWActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonM);
        jRadioButtonM.setText("Man");

        btnAddMemeber.setText("Add");
        btnAddMemeber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMemeberActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonStaff);
        jRadioButtonStaff.setText("University Staff");
        jRadioButtonStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonStaffActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonStudent);
        jRadioButtonStudent.setText("Student");
        jRadioButtonStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonStudentActionPerformed(evt);
            }
        });

        jLabel4.setText("Study Course");

        jComboBoxCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT. Programming", "ICT. Cyber Security", "ICT. Network", "ICT. DataBase" }));
        jComboBoxCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCourseActionPerformed(evt);
            }
        });

        jLabel5.setText("Are you in a sports Team?");

        buttonGroup4.add(jRadioButtonTeamY);
        jRadioButtonTeamY.setText("Yes");
        jRadioButtonTeamY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTeamYActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRadioButtonTeamN);
        jRadioButtonTeamN.setText("No");
        jRadioButtonTeamN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTeamNActionPerformed(evt);
            }
        });

        jComboBoxTeam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vollyball", "basketball", "football", "running", "tennis" }));
        jComboBoxTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTeamLayout = new javax.swing.GroupLayout(pnlTeam);
        pnlTeam.setLayout(pnlTeamLayout);
        pnlTeamLayout.setHorizontalGroup(
            pnlTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTeamLayout.createSequentialGroup()
                .addComponent(jComboBoxTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 300, Short.MAX_VALUE))
        );
        pnlTeamLayout.setVerticalGroup(
            pnlTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTeamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlStudentLayout = new javax.swing.GroupLayout(pnlStudent);
        pnlStudent.setLayout(pnlStudentLayout);
        pnlStudentLayout.setHorizontalGroup(
            pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(jComboBoxCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButtonTeamY)
                    .addComponent(jRadioButtonTeamN)))
        );
        pnlStudentLayout.setVerticalGroup(
            pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStudentLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4))
                    .addComponent(jComboBoxCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonTeamY)
                .addGap(12, 12, 12)
                .addComponent(jRadioButtonTeamN)
                .addGap(3, 3, 3)
                .addComponent(pnlTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblPosition.setText("Department");

        txtPosition.setColumns(10);

        lblDepartment.setText("Position");

        jComboBoxDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT", "Creative Media", "Engineering", "Business", "Adminstration", "Health & sanitary", "Services" }));
        jComboBoxDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStaffLayout = new javax.swing.GroupLayout(pnlStaff);
        pnlStaff.setLayout(pnlStaffLayout);
        pnlStaffLayout.setHorizontalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPosition)
                    .addComponent(lblDepartment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        pnlStaffLayout.setVerticalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPosition)
                    .addComponent(jComboBoxDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDepartment)
                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMemberTypeLayout = new javax.swing.GroupLayout(pnlMemberType);
        pnlMemberType.setLayout(pnlMemberTypeLayout);
        pnlMemberTypeLayout.setHorizontalGroup(
            pnlMemberTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemberTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlMemberTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 774, Short.MAX_VALUE))
        );
        pnlMemberTypeLayout.setVerticalGroup(
            pnlMemberTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemberTypeLayout.createSequentialGroup()
                .addComponent(pnlStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 118, Short.MAX_VALUE))
            .addGroup(pnlMemberTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMemberTypeLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblPhone1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblFname1)
                                        .addComponent(lblLName1))
                                    .addGap(62, 62, 62)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtLName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtfName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbladdress1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDOB, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonW)
                                        .addGap(55, 55, 55)
                                        .addComponent(jRadioButtonM))))
                            .addComponent(btnAddMemeber))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonStudent)
                                    .addComponent(jRadioButtonStaff)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(pnlMemberType, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jRadioButtonStaff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonStudent)
                        .addGap(18, 18, 18)
                        .addComponent(pnlMemberType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFname1)
                            .addComponent(txtfName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLName1)
                            .addComponent(txtLName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbladdress1)
                            .addComponent(txtaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone1)
                            .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDOB)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jRadioButtonW)
                            .addComponent(jRadioButtonM))
                        .addGap(48, 48, 48)
                        .addComponent(btnAddMemeber)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Add Member", jPanel2);

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 102, 102));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHome)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Name: AssignTrainerButtonActionPerfomed
     *
     * @author Fatima Alrafaei Purpose/description: takes selected trainer and
     * member and assigns the member to the trainer allowed to run in the race
     * @param
     * @return *
     */
    private void AssignTrainerButtonActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String selectedTrainer = TrainerComboBox.getSelectedItem().toString();
            String selectedMember = MemberComboBox.getSelectedItem().toString();
            int i = 0;
            do {

                if (Gym.getEmployeesList().get(i) instanceof Trainer) {

                    Trainer trainer = (Trainer) Gym.getEmployeesList().get(i);
                    String trainerName = trainer.getfName() + " " + trainer.getlName();
                    if (trainerName.equals(selectedTrainer)) {
                        int j = 0;
                        do {

                            Member member = Gym.getMembersList().get(j);
                            String memberName = member.getfName() + " " + member.getlName();
                            if (memberName.equals(selectedMember)) {
                                if (trainer.getAssignedMembers().contains(member)) {
                                    throw new Exception("Member is already assigned to a trainer!");
                                }
                                trainer.getAssignedMembers().add(member);
                                JOptionPane.showMessageDialog(rootPane, "Member is assigned successfully");
                                // update comboBoxes
                                loadUnassignedMembers();
                                loadTrainerMembers();
                                return;
                            }
                            j++;
                        } while (j < Gym.getMembersList().size());
                    }

                }
                i++;
            } while (i < Gym.getEmployeesList().size());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void TrainerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {

    }

    /**
     * Name: loadUnassignedMembers
     *
     * @author Dana Alajmi Purpose/description: get the list of members that are
     * not in any trainer's members list
     */
    private void loadUnassignedMembers() {
        MemberComboBox.removeAllItems();

        for (Member member : Gym.getMembersList()) {
            boolean isAssigned = false;

            for (Employee employee : Gym.getEmployeesList()) {
                if (employee instanceof Trainer) {
                    Trainer trainer = (Trainer) employee;

                    for (Member assignedMember : trainer.getAssignedMembers()) {
                        if (assignedMember.getMembershipID() == member.getMembershipID()) {
                            isAssigned = true;
                            break;
                        }
                    }
                }

                if (isAssigned) {
                    break;
                }
            }

            if (!isAssigned) {
                MemberComboBox.addItem(member.getfName() + " " + member.getlName());
            }
        }
    }

    private void jComboBoxDepActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jComboBoxTeamActionPerformed(java.awt.event.ActionEvent evt) {

    }

    /**
     * Name: jRadioButtonTeamYActionPerformed
     *
     *
     * @author Dana Alajmi Purpose/description: show the team panel if the
     * button is selected
     */
    private void jRadioButtonTeamYActionPerformed(java.awt.event.ActionEvent evt) {

        if (jRadioButtonTeamY.isSelected()) {
            pnlTeam.setVisible(true);

        }
    }

    private void jComboBoxCourseActionPerformed(java.awt.event.ActionEvent evt) {

    }

    /**
     * Name: jRadioButtonStudentActionPerformed
     *
     * @author Dana Alajmi Purpose/description: show student info panel and hide
     * staff & team panels
     */
    private void jRadioButtonStudentActionPerformed(java.awt.event.ActionEvent evt) {

        if (jRadioButtonStudent.isSelected()) {

            pnlStudent.setVisible(true);
            pnlStaff.setVisible(false);
            pnlTeam.setVisible(false);
        }
    }

    /**
     * Name: jRadioButtonStaffActionPerformed
     *
     * @author Dana Alajmi Purpose/description: show staff info panel and hide
     * student
     */
    private void jRadioButtonStaffActionPerformed(java.awt.event.ActionEvent evt) {

        if (jRadioButtonStaff.isSelected()) {
            pnlStudent.setVisible(false);
            pnlStaff.setVisible(true);
        }
    }

    /**
     * Name: txtDOBMouseClicked
     *
     * @author Dana Alajmi Purpose/description: clear Date of birth field from
     * the placeholder
     */
    private void txtDOBMouseClicked(java.awt.event.MouseEvent evt) {

        txtDOB.setText(null);
    }

    private void jRadioButtonWActionPerformed(java.awt.event.ActionEvent evt) {

    }

    /**
     * Name: btnAddMemeberActionPerformed
     *
     * @author Dana Alajmi Purpose/description: take in user input and create a
     * member, update unassigned members combobox
     */
    private void btnAddMemeberActionPerformed(java.awt.event.ActionEvent evt) {

        try {
            Member newMember = null;
            String fname = txtfName1.getText();
            String lname = txtLName1.getText();
            String address = txtaddress1.getText();
            int phone = Integer.parseInt(txtPhone1.getText());
            String DOB = txtDOB.getText();
            String gender = null;
            if (jRadioButtonW.isSelected()) {
                gender = "Female";
            } else if (jRadioButtonM.isSelected()) {
                gender = "Male";
            }
            if (jRadioButtonStudent.isSelected()) {
                String type = "student";
                String course = jComboBoxCourse.getSelectedItem().toString();
                if (jRadioButtonTeamY.isSelected()) {
                    String team = jComboBoxTeam.getSelectedItem().toString();
                    newMember = new Student(course, team, DOB, gender, type, fname, lname, address, phone);
                } else if (jRadioButtonTeamN.isSelected()) {
                    newMember = new Student(course, DOB, gender, type, fname, lname, address, phone);
                }
            } else if (jRadioButtonStaff.isSelected()) {
                String position = txtPosition.getText();
                String type = "Staff";
                String department = jComboBoxDep.getSelectedItem().toString();
                newMember = new Staff(position, department, DOB, gender, type, fname, lname, address, phone);

            }
            Gym.addMember(newMember);
            String fullName = fname + " " + lname;
            loadUnassignedMembers(); // add to combo box

            try {
                FileOutputStream fileOut = new FileOutputStream("members.dat");
                ObjectOutputStream out = new ObjectOutputStream(fileOut);
                out.writeObject(Gym.getMembersList());
                out.writeInt(Member.getID());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(this, "Member Added to gym!", "Success", HEIGHT);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex, "Expected a number", HEIGHT);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, ex, "Object has not been initialized", HEIGHT);
        }
    }

    private void MemberComboBoxActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void TrainerMemberComboBoxActionPerformed(java.awt.event.ActionEvent evt) {

    }

    /**
     * Name: RemoveMemberButton1ActionPerformed
     *
     * @author Fatima Alrafaei Purpose/description: remove member from their
     * trainer
     */
    private void RemoveMemberButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String selectedTrainer = TrainerComboBox.getSelectedItem().toString();
        String selectedMember = TrainerMemberComboBox.getSelectedItem().toString();
        for (Employee emp : Gym.getEmployeesList()) {
            if (emp instanceof Trainer) {
                Trainer trainer = (Trainer) emp;
                String trainerName = trainer.getfName() + " " + trainer.getlName();
                if (trainerName.equals(selectedTrainer)) {
                    for (int i = 0; i < trainer.getAssignedMembers().size(); i++) {
                        Member member = trainer.getAssignedMembers().get(i);
                        String memberName = member.getfName() + " " + member.getlName();
                        if (memberName.equals(selectedMember)) {
                            trainer.getAssignedMembers().remove(i);
                            JOptionPane.showMessageDialog(rootPane, "Member removed successfully");
                            loadTrainerMembers();
                            loadUnassignedMembers();
                            try {
                                FileOutputStream fileempOut = new FileOutputStream("employees.dat");
                                ObjectOutputStream empout = new ObjectOutputStream(fileempOut);
                                empout.writeObject(Gym.getEmployeesList());
                                empout.writeInt(Employee.getID());
                            } catch (IOException ex) {
                                Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }
                }
            }
        }

    }

    private void TrainerComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {
        loadTrainerMembers();

    }
    // private void jRadioButtonStaffActionPerformed(java.awt.event.ActionEvent evt)
     // {//GEN-FIRST:event_jRadioButtonStaffActionPerformed
     //
    // if(jRadioButtonStaff.isSelected()){
    // pnlStudent.setVisible(false);
    // pnlStaff.setVisible(true);
    // }
     // }//GEN-LAST:event_jRadioButtonStaffActionPerformed

    // private void jRadioButtonStudentActionPerformed(java.awt.event.ActionEvent
    // evt) {//GEN-FIRST:event_jRadioButtonStudentActionPerformed
    //
    // if(jRadioButtonStudent.isSelected()){
    // pnlStudent.setVisible(true);
    // pnlStaff.setVisible(false);
    // pnlTeam.setVisible(false);
    // }
    // }//GEN-LAST:event_jRadioButtonStudentActionPerformed
    // private void jRadioButtonTeamYActionPerformed(java.awt.event.ActionEvent evt)
    // {//GEN-FIRST:event_jRadioButtonTeamYActionPerformed
    //
    // if(jRadioButtonTeamY.isSelected()){
    // pnlTeam.setVisible(true);
    // }
    // }//GEN-LAST:event_jRadioButtonTeamYActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed
        /**
     * Name: btnHomeActionPerformed
     *
     * @author Dana Alajmi Purpose/description: open mainWindow
     */
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {

        this.setVisible(false);

        try {
            new MainWindow().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Name: jTabbedPane1StateChanged
     *
     * @author Noor Kamal Purpose/description: loads appropriate data if user
     * selects Delete Members panel
     */
    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {

        int selectedIndex = jTabbedPane1.getSelectedIndex();
        String tabTitle = jTabbedPane1.getTitleAt(selectedIndex);

        if ("Delete Members".equals(tabTitle)) {
            loadMembersFromFile();
            loadMembersIntoTable();

        }

    }

    /**
     * Name: jButtonDeleteActionPerformed
     *
     * @author Noor Kamal Purpose/description: Deletes members from ArrayList
     * add serializes them
     */
    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {

        int selectedRow = jTableMembers.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a member to delete.");
            return;
        }

        // Get Member ID and Name from the selected row
        int membershipId = (int) jTableMembers.getValueAt(selectedRow, 0);
        String fname = (String) jTableMembers.getValueAt(selectedRow, 1);
        String lname = (String) jTableMembers.getValueAt(selectedRow, 2);

        // Show confirmation dialog
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete member " + fname + " " + lname + "?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION
        );

        if (choice != JOptionPane.YES_OPTION) {
            return; // user clicked No, cancel deletion
        }

        // Find the member object
        Member toRemove = null;
        for (Member m : Gym.getMembersList()) {
            if (m.getMembershipID() == membershipId) {
                toRemove = m;
                break;
            }
        }

        if (toRemove == null) {
            JOptionPane.showMessageDialog(this, "Member not found.");
            return;
        }

        // 🔑 Business rule: remove from any trainer’s assigned list
        boolean removedFromTrainer = false;
        for (Employee e : Gym.getEmployeesList()) {
            if (e instanceof Trainer) {
                Trainer t = (Trainer) e;
                if (t.getAssignedMembers().remove(toRemove)) {
                    removedFromTrainer = true;
                }
            }
        }
    }

    private void txtTeamDisplyM_EActionPerformed(java.awt.event.ActionEvent evt) {

    }

    /**
     * Name: ComboBoxTeamM_EActionPerformed
     *
     * @author Fatima Hussain Purpose/description: set team field to selection
     */
    private void ComboBoxTeamM_EActionPerformed(java.awt.event.ActionEvent evt) {

        String AlteredTeam = ComboBoxTeamM_E.getSelectedItem().toString();
        txtTeamDisplyM_E.setText(AlteredTeam);

    }

    /**
     * Name: ComboBoxTeamM_EActionPerformed
     *
     * @author Fatima Hussain Purpose/description: set team field to selection
     */
    private void ComboBoxCourseM_EActionPerformed(java.awt.event.ActionEvent evt) {

        String AlteredCourse = ComboBoxCourseM_E.getSelectedItem().toString();
        txtCourseDisplyM_E.setText(AlteredCourse);

    }

    /**
     * Name: btnAlterMemeberSaveActionPerformed
     *
     * @author Fatima Hussain Purpose/description: Update members and serialize
     */
    private void btnAlterMemeberSaveActionPerformed(java.awt.event.ActionEvent evt) {

        FileOutputStream fileOut = null;
        try {

            //
            int id = Integer.parseInt(jComboBoxMembersID.getSelectedItem().toString());// take id from combo
            for (int i = 0; i < Gym.getMembersList().size(); i++) {

                if (Gym.getMembersList().get(i).getMembershipID() == id) { // search for same id from the loop
                    Gym.getMembersList().get(i).setfName(txtfNameM_E.getText()); // if id found we gonna set new info in
                    // the array list
                    Gym.getMembersList().get(i).setlName(txtLNameM_E.getText());
                    Gym.getMembersList().get(i).setAddress(txtaddressM_E.getText());
                    Gym.getMembersList().get(i).setDateOfBirth(txtDOBM_E.getText());
                    Gym.getMembersList().get(i).setPhone(Integer.parseInt(txtPhoneM_E.getText()));
                    Gym.getMembersList().get(i).setGender(txtGenderM_E.getText());
                    Gym.getMembersList().get(i).setType(txtMemberTypeM_E.getText());
                    if (Gym.getMembersList().get(i) instanceof Staff) {
                        ((Staff) Gym.getMembersList().get(i)).setPosition(txtPosition1.getText());
                        ((Staff) Gym.getMembersList().get(i)).setDepartment(txtDisplayDepartment.getText());
                    } else if (Gym.getMembersList().get(i) instanceof Student) {
                        ((Student) Gym.getMembersList().get(i)).setCourse(txtCourseDisplyM_E.getText());
                        ((Student) Gym.getMembersList().get(i)).setTeam(txtTeamDisplyM_E.getText());

                    }
                    // then we going to disply new info in the combo that got saved in the array
                    // previously

                    txtfNameM_E.setText(Gym.getMembersList().get(i).getfName());
                    txtLNameM_E.setText(Gym.getMembersList().get(i).getlName());
                    txtaddressM_E.setText(Gym.getMembersList().get(i).getAddress());
                    txtDOBM_E.setText(Gym.getMembersList().get(i).getDateOfBirth());
                    txtPhoneM_E.setText(Integer.toString(Gym.getMembersList().get(i).getPhone()));
                    txtGenderM_E.setText(Gym.getMembersList().get(i).getGender());
                    txtMemberTypeM_E.setText(Gym.getMembersList().get(i).getType());
                    if (Gym.getMembersList().get(i) instanceof Staff) {
                        txtPosition1.setText(((Staff) Gym.getMembersList().get(i)).getPosition());
                        txtDisplayDepartment.setText(((Staff) Gym.getMembersList().get(i)).getDepartment());
                    } else if (Gym.getMembersList().get(i) instanceof Student) {
                        txtCourseDisplyM_E.setText(((Student) Gym.getMembersList().get(i)).getCourse());
                        txtTeamDisplyM_E.setText(((Student) Gym.getMembersList().get(i)).getTeam());
                    }
                    break;

                }

            }
            initialiseCombo();

            fileOut = new FileOutputStream("Members.dat");
            ObjectOutputStream out = null;
            try {
                out = new ObjectOutputStream(fileOut);
            } catch (IOException ex) {
                Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Member's Data Altered Successfully");
            out.writeObject(Gym.getMembersList());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileOut.close();
            } catch (IOException ex) {
                Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    /**
     * Name: jRadioButtonWM_EActionPerformed
     *
     * @author Fatima Hussain Purpose/description: set gender field to selection
     */
    private void jRadioButtonWM_EActionPerformed(java.awt.event.ActionEvent evt) {

        txtGenderM_E.setText("Female");

    }

    /**
     * Name: jComboBoxMembersIDActionPerformed
     *
     * @author Fatima Hussain Purpose/description: take in the ID from the combo
     * box and set fields from it's data
     */
    private void jComboBoxMembersIDActionPerformed(java.awt.event.ActionEvent evt) {

        Object selected = jComboBoxMembersID.getSelectedItem();
        if (selected != null) {
            int selection = Integer.parseInt(selected.toString());
            for (Member members : Gym.getMembersList()) {
                if (members.getMembershipID() == selection) {
                    txtfNameM_E.setText(members.getfName());
                    txtLNameM_E.setText(members.getlName());
                    txtaddressM_E.setText(members.getAddress());
                    txtDOBM_E.setText(members.getDateOfBirth());
                    txtPhoneM_E.setText(Integer.toString(members.getPhone()));
                    txtGenderM_E.setText(members.getGender());
                    txtMemberTypeM_E.setText(members.getType());
                    if (members instanceof Student) {
                        txtCourseDisplyM_E.setText(((Student) members).getCourse());
                        if (((Student) members).getTeam() != null) {
                            txtTeamDisplyM_E.setText(((Student) members).getTeam());
                        } else {
                            txtTeamDisplyM_E.setText("None");
                        }
                    }
                    if (members instanceof Staff) {
                        txtDisplayDepartment.setText(((Staff) members).getDepartment());
                        txtPosition1.setText(((Staff) members).getPosition());

                        pnlStudent1.setVisible(false);
                        pnlStaff1.setVisible(true);

                    } else {
                        pnlStudent1.setVisible(true);
                        pnlStaff1.setVisible(false);
                    }

                    break;

                }
            }
        }

    }

    /**
     * Name: jRadioButtonMM_EActionPerformed
     *
     * @author Fatima Hussain Purpose/description: set gender field to selection
     */
    private void jRadioButtonMM_EActionPerformed(java.awt.event.ActionEvent evt) {

        txtGenderM_E.setText("Male");
    }

    /**
     * Name: jComboBoxDep1ActionPerformed
     *
     * @author Fatima Hussain Purpose/description: set department field to
     * selection
     */
    private void jComboBoxDep1ActionPerformed(java.awt.event.ActionEvent evt) {

        txtDisplayDepartment.setText(jComboBoxDep1.getSelectedItem().toString());

    }

    /**
     * Name: jRadioButtonTeamNActionPerformed
     *
     * @author Dana Alajmi Purpose/description: hide team panel if student isn't
     * in a team
     */
    private void jRadioButtonTeamNActionPerformed(java.awt.event.ActionEvent evt) {

        if (jRadioButtonTeamN.isSelected()) {

            pnlTeam.setVisible(false);

        }
    }

    /**
     * Name: loadMembersFromFile
     *
     * @author Noor Kamal Purpose/description: deserialise members.dat
     */
    private void loadMembersFromFile() {

        try (FileInputStream fileIn = new FileInputStream("members.dat"); ObjectInputStream in = new ObjectInputStream(fileIn)) {

            ArrayList<Member> savedList = (ArrayList<Member>) in.readObject();
            Gym.setMembersList(savedList); // update Gym’s list

        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "No saved members yet.");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading Mmebers: " + e.getMessage());
        }
    }

    /**
     * Name: loadMembersIntoTable
     *
     * @author Noor Kamal Purpose/description: populate table with member data
     */
    private void loadMembersIntoTable() {
        String[] columns = {"Membership Id", "First Name", "Last Name", "Phone Number"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        for (Member m : Gym.getMembersList()) {
            Object[] row = {
                m.getMembershipID(),
                m.getfName(),
                m.getlName(),
                m.getPhone()

            };
            model.addRow(row);
        }

        jTableMembers.setModel(model);
    }

    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }

        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignTrainerButton;
    private javax.swing.JComboBox<String> ComboBoxCourseM_E;
    private javax.swing.JComboBox<String> ComboBoxTeamM_E;
    private javax.swing.JComboBox<String> MemberComboBox;
    private javax.swing.JToggleButton RemoveMemberButton1;
    private javax.swing.JComboBox<String> TrainerComboBox;
    private javax.swing.JComboBox<String> TrainerComboBox2;
    private javax.swing.JComboBox<String> TrainerMemberComboBox;
    private javax.swing.JButton btnAddMemeber;
    private javax.swing.JButton btnAlterMemeberSave;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JComboBox<String> jComboBoxCourse;
    private javax.swing.JComboBox<String> jComboBoxDep;
    private javax.swing.JComboBox<String> jComboBoxDep1;
    private javax.swing.JComboBox<String> jComboBoxMembersID;
    private javax.swing.JComboBox<String> jComboBoxTeam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButtonM;
    private javax.swing.JRadioButton jRadioButtonMM_E;
    private javax.swing.JRadioButton jRadioButtonStaff;
    private javax.swing.JRadioButton jRadioButtonStudent;
    private javax.swing.JRadioButton jRadioButtonTeamN;
    private javax.swing.JRadioButton jRadioButtonTeamY;
    private javax.swing.JRadioButton jRadioButtonW;
    private javax.swing.JRadioButton jRadioButtonWM_E;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableMembers;
    private javax.swing.JLabel lblAlterMemberTitle;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOBM_E;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDepartment1;
    private javax.swing.JLabel lblFname1;
    private javax.swing.JLabel lblFnameM_E;
    private javax.swing.JLabel lblFnameM_E1;
    private javax.swing.JLabel lblGenderM_E;
    private javax.swing.JLabel lblLName1;
    private javax.swing.JLabel lblLNameM_E;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblPhoneM_E;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblPosition1;
    private javax.swing.JLabel lblSportTeamM_E;
    private javax.swing.JLabel lblStuduyCourseM_E;
    private javax.swing.JLabel lbladdress1;
    private javax.swing.JLabel lbladdressM_E;
    private javax.swing.JPanel pnlJoin;
    private javax.swing.JPanel pnlMemberType;
    private javax.swing.JPanel pnlStaff;
    private javax.swing.JPanel pnlStaff1;
    private javax.swing.JPanel pnlStudent;
    private javax.swing.JPanel pnlStudent1;
    private javax.swing.JPanel pnlTeam;
    private javax.swing.JTextField txtCourseDisplyM_E;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDOBM_E;
    private javax.swing.JTextField txtDisplayDepartment;
    private javax.swing.JTextField txtGenderM_E;
    private javax.swing.JTextField txtLName1;
    private javax.swing.JTextField txtLNameM_E;
    private javax.swing.JTextField txtMemberTypeM_E;
    private javax.swing.JTextField txtPhone1;
    private javax.swing.JTextField txtPhoneM_E;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtPosition1;
    private javax.swing.JTextField txtTeamDisplyM_E;
    private javax.swing.JTextField txtaddress1;
    private javax.swing.JTextField txtaddressM_E;
    private javax.swing.JTextField txtfName1;
    private javax.swing.JTextField txtfNameM_E;
    // End of variables declaration//GEN-END:variables

    private void initialiseCombo() {
        if (Gym.getMembersList() != null) {
            jComboBoxMembersID.removeAllItems();
        }
        for (Member members : Gym.getMembersList()) {

            int item = members.getMembershipID();
            jComboBoxMembersID.addItem(Integer.toString(item));

        }

    }
}
