package GUI;

/**
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt
 * to change this license Click
 * nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this
 * template
 */
import GUI.MainWindow;
import LOGIC.Gym;
import LOGIC.Member;
import LOGIC.Staff;
import LOGIC.Student;
import LOGIC.Employee;
import LOGIC.Trainer;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.RootPaneUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danalajmi
 */
public class MemberDisplay extends javax.swing.JFrame {

    /**
     * Creates new form MemberDisplay
     */
    public MemberDisplay() {
        initComponents();
        AddTrainers();
        loadTrainerMembers();

    }

    public void AddTrainers() {
        int i = 0;
        do {
            Employee employee = Gym.getEmployeesList().get(i);
            if (employee instanceof Trainer) {
                Trainer trainer = (Trainer) employee;
                String fullName = trainer.getfName() + " " + trainer.getlName();
                TrainerComboBox.addItem(fullName);
                TrainerComboBox2.addItem(fullName);

            }
            i++;
        } while (i < Gym.getEmployeesList().size());
    }

    public void loadTrainerMembers() {
        if (TrainerComboBox.getSelectedItem() != null) {
            TrainerMemberComboBox.removeAllItems();
            String selectedTrainer = TrainerComboBox.getSelectedItem().toString();
            for (Employee employee : Gym.getEmployeesList()) {
                if (employee instanceof Trainer) {
                    Trainer trainer = (Trainer) employee;
                    String trainerName = trainer.getfName() + " " + trainer.getlName();
                    if (trainerName.equals(selectedTrainer)) {
                        if (trainer.getAssignedMembers() != null) {
                            for (Member member : trainer.getAssignedMembers()) {
                                String memberName = member.getfName() + " " + member.getlName();
                                TrainerMemberComboBox.addItem(memberName);
                            }
                        }

                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFname1 = new javax.swing.JLabel();
        txtfName1 = new javax.swing.JTextField();
        lblLName1 = new javax.swing.JLabel();
        txtLName1 = new javax.swing.JTextField();
        lbladdress1 = new javax.swing.JLabel();
        txtaddress1 = new javax.swing.JTextField();
        lblPhone1 = new javax.swing.JLabel();
        txtPhone1 = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonW = new javax.swing.JRadioButton();
        jRadioButtonM = new javax.swing.JRadioButton();
        btnAddMemeber = new javax.swing.JButton();
        jRadioButtonStaff = new javax.swing.JRadioButton();
        jRadioButtonStudent = new javax.swing.JRadioButton();
        pnlMemberType = new javax.swing.JPanel();
        pnlStudent = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxCourse = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonTeamY = new javax.swing.JRadioButton();
        jRadioButtonTeamN = new javax.swing.JRadioButton();
        pnlTeam = new javax.swing.JPanel();
        jComboBoxTeam = new javax.swing.JComboBox<>();
        pnlStaff = new javax.swing.JPanel();
        lblPosition = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();
        jComboBoxDep = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        TrainerComboBox = new javax.swing.JComboBox<>();
        AssignTrainerButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MemberComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        TrainerComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TrainerMemberComboBox = new javax.swing.JComboBox<>();
        RemoveMemberButton1 = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMembers = new javax.swing.JTable();
        jButtonDelete = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Add member");

        lblFname1.setText("First name: ");

        txtfName1.setColumns(10);
        txtfName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfName1ActionPerformed(evt);
            }
        });

        lblLName1.setText("Last name: ");

        txtLName1.setColumns(10);
        txtLName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLName1ActionPerformed(evt);
            }
        });

        lbladdress1.setText("address");

        txtaddress1.setColumns(10);
        txtaddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddress1ActionPerformed(evt);
            }
        });

        lblPhone1.setText("phone Number");

        txtPhone1.setColumns(10);
        txtPhone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhone1ActionPerformed(evt);
            }
        });

        lblDOB.setText("Date of birth");

        txtDOB.setColumns(10);
        txtDOB.setText("DD/MM/YYYY");
        txtDOB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDOBMouseClicked(evt);
            }
        });

        jLabel3.setText("Gender: ");

        jRadioButtonW.setText("Woman");
        jRadioButtonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonWActionPerformed(evt);
            }
        });

        jRadioButtonM.setText("Man");

        btnAddMemeber.setText("Add");
        btnAddMemeber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMemeberActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonStaff);
        jRadioButtonStaff.setText("University Staff");
        jRadioButtonStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonStaffActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonStudent);
        jRadioButtonStudent.setText("Student");
        jRadioButtonStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonStudentActionPerformed(evt);
            }
        });

        pnlStudent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Study Course");
        pnlStudent.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, -1, -1));

        jComboBoxCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT. Programming", "ICT. Cyber Security", "ICT. Network", "ICT. DataBase" }));
        jComboBoxCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCourseActionPerformed(evt);
            }
        });
        pnlStudent.add(jComboBoxCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 29, -1, -1));

        jLabel5.setText("Are you in a sports Team?");
        pnlStudent.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 68, -1, -1));

        jRadioButtonTeamY.setText("Yes");
        jRadioButtonTeamY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTeamYActionPerformed(evt);
            }
        });
        pnlStudent.add(jRadioButtonTeamY, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 103, -1, -1));

        jRadioButtonTeamN.setText("No");
        jRadioButtonTeamN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTeamNActionPerformed(evt);
            }
        });
        pnlStudent.add(jRadioButtonTeamN, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 136, -1, -1));

        jComboBoxTeam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vollyball", "basketball", "football", "running", "tennis" }));
        jComboBoxTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTeamLayout = new javax.swing.GroupLayout(pnlTeam);
        pnlTeam.setLayout(pnlTeamLayout);
        pnlTeamLayout.setHorizontalGroup(
            pnlTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTeamLayout.createSequentialGroup()
                .addComponent(jComboBoxTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 300, Short.MAX_VALUE))
        );
        pnlTeamLayout.setVerticalGroup(
            pnlTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTeamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pnlStudent.add(pnlTeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        lblPosition.setText("Department");

        txtPosition.setColumns(10);

        lblDepartment.setText("Position");

        jComboBoxDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT", "Creative Media", "Engineering", "Business", "Adminstration", "Health & sanitary", "Services" }));
        jComboBoxDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStaffLayout = new javax.swing.GroupLayout(pnlStaff);
        pnlStaff.setLayout(pnlStaffLayout);
        pnlStaffLayout.setHorizontalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPosition)
                    .addComponent(lblDepartment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        pnlStaffLayout.setVerticalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPosition)
                    .addComponent(jComboBoxDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDepartment)
                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMemberTypeLayout = new javax.swing.GroupLayout(pnlMemberType);
        pnlMemberType.setLayout(pnlMemberTypeLayout);
        pnlMemberTypeLayout.setHorizontalGroup(
            pnlMemberTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemberTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlMemberTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 774, Short.MAX_VALUE))
        );
        pnlMemberTypeLayout.setVerticalGroup(
            pnlMemberTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemberTypeLayout.createSequentialGroup()
                .addComponent(pnlStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 118, Short.MAX_VALUE))
            .addGroup(pnlMemberTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMemberTypeLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblPhone1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblFname1)
                                        .addComponent(lblLName1))
                                    .addGap(62, 62, 62)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtLName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtfName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbladdress1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDOB, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonW)
                                        .addGap(55, 55, 55)
                                        .addComponent(jRadioButtonM))))
                            .addComponent(btnAddMemeber))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonStudent)
                                    .addComponent(jRadioButtonStaff)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(pnlMemberType, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jRadioButtonStaff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonStudent)
                        .addGap(18, 18, 18)
                        .addComponent(pnlMemberType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFname1)
                            .addComponent(txtfName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLName1)
                            .addComponent(txtLName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbladdress1)
                            .addComponent(txtaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone1)
                            .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDOB)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jRadioButtonW)
                            .addComponent(jRadioButtonM))
                        .addGap(48, 48, 48)
                        .addComponent(btnAddMemeber)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Add Member", jPanel2);

        TrainerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainerComboBoxActionPerformed(evt);
            }
        });

        AssignTrainerButton.setText("Assign");
        AssignTrainerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignTrainerButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Select a member");

        jLabel6.setText("Select a Trainer");

        MemberComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberComboBoxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel9.setText("Assign a Trainer to a Member ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MemberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TrainerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssignTrainerButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel9)))
                .addContainerGap(350, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel9)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MemberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TrainerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(AssignTrainerButton)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Assign Trainer ", jPanel1);

        TrainerComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainerComboBox2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Select Trainer ");

        jLabel8.setText("Select the member you want to remove");

        TrainerMemberComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainerMemberComboBoxActionPerformed(evt);
            }
        });

        RemoveMemberButton1.setText("Remove");
        RemoveMemberButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveMemberButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel10.setText("Remove a Member fram a Trainer List");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(19, 19, 19)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TrainerMemberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TrainerComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RemoveMemberButton1)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel10)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel10)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TrainerComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TrainerMemberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(RemoveMemberButton1)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Remove Member ", jPanel3);

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel11.setText("Delete Members");

        jLabel12.setText("This feature will delete membership of members from the gym");

        jTableMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Membership ID", "First Name", "Last Name", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMembers);

        jButtonDelete.setText("Delete Membership");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(307, 307, 307))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jButtonDelete)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonDelete)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Delete Members", jPanel4);

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnHome)
                .addGap(32, 32, 32)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AssignTrainerButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AssignTrainerButtonActionPerformed
        try {
            String selectedTrainer = TrainerComboBox.getSelectedItem().toString();
            String selectedMember = MemberComboBox.getSelectedItem().toString();
            int i = 0;
            do {

                Trainer trainer = (Trainer) Gym.getEmployeesList().get(i);
                String trainerName = trainer.getfName() + " " + trainer.getlName();
                if (trainerName.equals(selectedTrainer)) {
                    int j = 0;
                    do {
                        Member member = Gym.getMembersList().get(j);
                        String memberName = member.getfName() + " " + member.getlName();
                        if (memberName.equals(selectedMember)) {
                            if (trainer.getAssignedMembers().contains(member)) {
                                throw new Exception("Member is already assigned to a trainer!");
                            }
                            trainer.getAssignedMembers().add(member);
                            JOptionPane.showMessageDialog(rootPane, "Member is assigned successfully");
                            return;
                        }
                        j++;
                    } while (j < Gym.getMembersList().size());
                }
                i++;
            } while (i < Gym.getEmployeesList().size());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }// GEN-LAST:event_AssignTrainerButtonActionPerformed

    private void TrainerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TrainerComboBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TrainerComboBoxActionPerformed

    private void jComboBoxDepActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jComboBoxTeamActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxTeamActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBoxTeamActionPerformed

    private void jRadioButtonTeamYActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (jRadioButtonTeamY.isSelected()) {
            pnlTeam.setVisible(true);

        }
    }

    private void jComboBoxCourseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxCourseActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBoxCourseActionPerformed

    private void jRadioButtonStudentActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (jRadioButtonStudent.isSelected()) {

            pnlStudent.setVisible(true);
            pnlStaff.setVisible(false);
            pnlTeam.setVisible(false);
        }
    }

    private void jRadioButtonStaffActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (jRadioButtonStaff.isSelected()) {
            pnlStudent.setVisible(false);
            pnlStaff.setVisible(true);
        }
    }

    private void txtfName1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtfName1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtfName1ActionPerformed

    private void txtLName1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtLName1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtLName1ActionPerformed

    private void txtaddress1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtaddress1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtaddress1ActionPerformed

    private void txtPhone1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPhone1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtPhone1ActionPerformed

    private void txtDOBMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_txtDOBMouseClicked
        // TODO add your handling code here:
        txtDOB.setText(null);
    }// GEN-LAST:event_txtDOBMouseClicked

    private void jRadioButtonWActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButtonWActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jRadioButtonWActionPerformed

    private void btnAddMemeberActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddMemeberActionPerformed
        // TODO add your handling code here:
        try {
            Member newMember = null;
            String fname = txtfName1.getText();
            String lname = txtLName1.getText();
            String address = txtaddress1.getText();
            int phone = Integer.parseInt(txtPhone1.getText());
            String DOB = txtDOB.getText();
            String gender = null;
            if (jRadioButtonW.isSelected()) {
                gender = "Female";
            } else if (jRadioButtonM.isSelected()) {
                gender = "Male";
            }
            if (jRadioButtonStudent.isSelected()) {
                String course = jComboBoxCourse.getSelectedItem().toString();
                if (jRadioButtonTeamY.isSelected()) {
                    String team = jComboBoxTeam.getSelectedItem().toString();
                    newMember = new Student(course, team, DOB, gender, team, fname, lname, address, phone);
                } else if (jRadioButtonTeamN.isSelected()) {
                    newMember = new Student(course, DOB, gender, DOB, fname, lname, address, phone);
                }
            } else if (jRadioButtonStaff.isSelected()) {
                String position = txtPosition.getText();
                String department = jComboBoxDep.getSelectedItem().toString();
                newMember = new Staff(position, department, DOB, gender, DOB, fname, lname, address, phone);

            }
            Gym.addMember(newMember);
            String fullName = fname + " " + lname;
            MemberComboBox.addItem(fullName); // add to combo box

            try {
                FileOutputStream fileOut = new FileOutputStream("members.dat");
                ObjectOutputStream out = new ObjectOutputStream(fileOut);
                out.writeObject(Gym.getMembersList());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(this, "Member Added to gym!", "Success", HEIGHT);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex, "Expected a number", HEIGHT);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, ex, "Object has not been initialized", HEIGHT);
        }
    }// GEN-LAST:event_btnAddMemeberActionPerformed

    private void MemberComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_MemberComboBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_MemberComboBoxActionPerformed

    private void TrainerMemberComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TrainerMemberComboBoxActionPerformed

        // TODO add your handling code here:
    }// GEN-LAST:event_TrainerMemberComboBoxActionPerformed

    private void RemoveMemberButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RemoveMemberButton1ActionPerformed
        String selectedTrainer = TrainerComboBox.getSelectedItem().toString();
        String selectedMember = TrainerMemberComboBox.getSelectedItem().toString();
        for (Employee emp : Gym.getEmployeesList()) {
            Trainer trainer = (Trainer) emp;
            String trainerName = trainer.getfName() + " " + trainer.getlName();
            if (trainerName.equals(selectedTrainer)) {
                for (int i = 0; i < trainer.getAssignedMembers().size(); i++) {
                    Member member = trainer.getAssignedMembers().get(i);
                    String memberName = member.getfName() + " " + member.getlName();
                    if (memberName.equals(selectedMember)) {
                        trainer.getAssignedMembers().remove(i);
                        JOptionPane.showMessageDialog(rootPane, "Member removed successfully");
                        loadTrainerMembers();
                    }
                }
            }
        }
        // TODO add your handling code here:
    }// GEN-LAST:event_RemoveMemberButton1ActionPerformed

    private void TrainerComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TrainerComboBox2ActionPerformed
        loadTrainerMembers();

    }// GEN-LAST:event_TrainerComboBox2ActionPerformed
    // private void jRadioButtonStaffActionPerformed(java.awt.event.ActionEvent evt)
     // {//GEN-FIRST:event_jRadioButtonStaffActionPerformed
     // // TODO add your handling code here:
    // if(jRadioButtonStaff.isSelected()){
    // pnlStudent.setVisible(false);
    // pnlStaff.setVisible(true);
    // }
     // }//GEN-LAST:event_jRadioButtonStaffActionPerformed

    // private void jRadioButtonStudentActionPerformed(java.awt.event.ActionEvent
    // evt) {//GEN-FIRST:event_jRadioButtonStudentActionPerformed
    // // TODO add your handling code here:
    // if(jRadioButtonStudent.isSelected()){
    // pnlStudent.setVisible(true);
    // pnlStaff.setVisible(false);
    // pnlTeam.setVisible(false);
    // }
    // }//GEN-LAST:event_jRadioButtonStudentActionPerformed
    // private void jRadioButtonTeamYActionPerformed(java.awt.event.ActionEvent evt)
    // {//GEN-FIRST:event_jRadioButtonTeamYActionPerformed
    // // TODO add your handling code here:
    // if(jRadioButtonTeamY.isSelected()){
    // pnlTeam.setVisible(true);
    // }
    // }//GEN-LAST:event_jRadioButtonTeamYActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        try {
            new MainWindow().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MemberDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHomeActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:

        int selectedIndex = jTabbedPane1.getSelectedIndex();
        String tabTitle = jTabbedPane1.getTitleAt(selectedIndex);

        if ("Delete Members".equals(tabTitle)) {
            loadMembersFromFile();
            loadMembersIntoTable();

        }

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTableMembers.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a member to delete.");
            return;
        }

        // Get Member ID and Name from the selected row
        int membershipId = (int) jTableMembers.getValueAt(selectedRow, 0);
        String fname = (String) jTableMembers.getValueAt(selectedRow, 1);
        String lname = (String) jTableMembers.getValueAt(selectedRow, 2);

        // Show confirmation dialog
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete member " + fname + " " + lname + "?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION
        );

        if (choice != JOptionPane.YES_OPTION) {
            return; // user clicked No, cancel deletion
        }

        // Find the member object
        Member toRemove = null;
        for (Member m : Gym.getMembersList()) {
            if (m.getMembershipID() == membershipId) {
                toRemove = m;
                break;
            }
        }

        if (toRemove == null) {
            JOptionPane.showMessageDialog(this, "Member not found.");
            return;
        }

        // 🔑 Business rule: remove from any trainer’s assigned list
        boolean removedFromTrainer = false;
        for (Employee e : Gym.getEmployeesList()) {
            if (e instanceof Trainer) {
                Trainer t = (Trainer) e;
                if (t.getAssignedMembers().remove(toRemove)) {
                    removedFromTrainer = true;
                }
            }
        }

        // Safe to delete from members list
        Gym.getMembersList().remove(toRemove);

        if (removedFromTrainer) {
            JOptionPane.showMessageDialog(this,
                    "Member deleted successfully and also removed from their trainer’s list.");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Member deleted successfully.");
        }

        // Save updated list back to file
        try (FileOutputStream fileOut = new FileOutputStream("members.dat"); ObjectOutputStream out = new ObjectOutputStream(fileOut)) {
            out.writeObject(Gym.getMembersList());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error saving updated members: " + ex.getMessage());
        }

        // Refresh table
        loadMembersIntoTable();
        loadTrainerMembers();


    }//GEN-LAST:event_jButtonDeleteActionPerformed
    private void jRadioButtonTeamNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButtonTeamNActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonTeamN.isSelected()) {

            pnlTeam.setVisible(true);

        }
    }
    // GEN-LAST:event_jRadioButtonTeamNActionPerformed

    /**
     * @param args the command line arguments
     */
    private void loadMembersFromFile() {

        try (FileInputStream fileIn = new FileInputStream("members.dat"); ObjectInputStream in = new ObjectInputStream(fileIn)) {

            ArrayList<Member> savedList = (ArrayList<Member>) in.readObject();
            Gym.setMembersList(savedList);   // update Gym’s list

        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "No saved members yet.");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading Mmebers: " + e.getMessage());
        }
    }

    private void loadMembersIntoTable() {
        String[] columns = {"Membership Id", "First Name", "Last Name", "Phone Number"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        for (Member m : Gym.getMembersList()) {
            Object[] row = {
                m.getMembershipID(),
                m.getfName(),
                m.getlName(),
                m.getPhone()

            };
            model.addRow(row);
        }

        jTableMembers.setModel(model);
    }

    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignTrainerButton;
    private javax.swing.JComboBox<String> MemberComboBox;
    private javax.swing.JToggleButton RemoveMemberButton1;
    private javax.swing.JComboBox<String> TrainerComboBox;
    private javax.swing.JComboBox<String> TrainerComboBox2;
    private javax.swing.JComboBox<String> TrainerMemberComboBox;
    private javax.swing.JButton btnAddMemeber;
    private javax.swing.JButton btnHome;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JComboBox<String> jComboBoxCourse;
    private javax.swing.JComboBox<String> jComboBoxDep;
    private javax.swing.JComboBox<String> jComboBoxTeam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonM;
    private javax.swing.JRadioButton jRadioButtonStaff;
    private javax.swing.JRadioButton jRadioButtonStudent;
    private javax.swing.JRadioButton jRadioButtonTeamN;
    private javax.swing.JRadioButton jRadioButtonTeamY;
    private javax.swing.JRadioButton jRadioButtonW;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableMembers;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblFname1;
    private javax.swing.JLabel lblLName1;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lbladdress1;
    private javax.swing.JPanel pnlMemberType;
    private javax.swing.JPanel pnlStaff;
    private javax.swing.JPanel pnlStudent;
    private javax.swing.JPanel pnlTeam;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtLName1;
    private javax.swing.JTextField txtPhone1;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtaddress1;
    private javax.swing.JTextField txtfName1;
    // End of variables declaration//GEN-END:variables
}
